---
#
# Copyright (C) 2018 Cumulus Networks, Inc. All rights reserved
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# https://www.debian.org/legal/licenses/mit
#
#
#
#
- hosts: network
  become: yes
  pre_tasks:
    # To prevent trying this demo on unsupported version, define the minimum Cumulus Linux
    # Release supported by this demo.
    - name: Verify Minimum Software Version
      assert:
        that: "{{ansible_lsb.release | version_compare('3.5', '>=') }}"
        msg: >
          "Cumulus Linux version must be 3.5 or later.
          Version {{ansible_lsb.release}} detected"

    - name: Turn off SSH rev DNS lookup
      lineinfile:
         path: /etc/ssh/sshd_config
         regexp: '^UseDNS '
         line: UseDNS no

    
    - name: Restart ssh
      service: name=sshd state=restarted

    - name: Add vagrant as a user to run net commands
      lineinfile:
         path: /etc/netd.conf
         regexp: '^users_with_show = root, cumulus'
         line: users_with_show = root, cumulus, vagrant
      tags:
         netd

    - name: Restart netd
      service: name=netd state=restarted
      tags:
         netd

  roles:
    - copy_interfaces
    - copy_frr_daemons
    - { role: mv_ntp_mgmt_vrf, when: ansible_hostname != 'edge01' }
    - restart_switches
      
- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Turn off SSH rev DNS lookup
      lineinfile:
         path: /etc/ssh/sshd_config
         regexp: '^UseDNS '
         line: UseDNS no

    
    - name: Restart ssh
      service: name=sshd state=restarted



  roles:
    - copy-int-reboot-servers
    
